In [1]:
import numpy as np
import pandas as pd 
import matplotlib as mlt
import seaborn as sns

In [16]:
df = pd.read_csv("Listings.csv", encoding="latin1")

C:\Users\sabba\AppData\Local\Temp\ipykernel_143200\1630855267.py:1: DtypeWarning: Columns (0: host_response_time, 1: district) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Listings.csv", encoding="latin1")

In [22]:
df.sample(5)

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
109537,40430258,fully furnished 1 BR at Ratchada17/ Sutthisan MRT,39669202,2015-07-27,"Bangkok, Thailand",within a day,0.9,0.00,f,119.0,...,30,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f
4968,3047718,NaN,15516356,2014-05-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f
239076,19908964,MySuiteInRome - Faboulus Suite in Trastevere,24059565,2014-11-23,"Rome, Lazio, Italy",within an hour,1.0,0.98,f,28.0,...,2,90,96.0,10.0,10.0,10.0,10.0,10.0,10.0,t
206947,25938492,Private rooms in cozy Manhattan apartment,194958383,2018-06-11,US,NaN,NaN,1.00,f,2.0,...,30,74,91.0,9.0,8.0,10.0,10.0,10.0,9.0,t
58365,36829930,Cozy studio with private garden,36053682,2015-06-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,0.0,...,3,1125,100.0,10.0,10.0,9.0,9.0,10.0,10.0,f

shape of data

In [4]:
df.shape

(279712, 33)

data type of data

In [6]:
df.info

<bound method DataFrame.info of         listing_id                                               name  \
0           281420     Beautiful Flat in le Village Montmartre, Paris
1          3705183                    39 mÃÂ² Paris (Sacre CÃ
âur)
2          4082273                Lovely apartment with Terrace, 60m2
3          4797344                Cosy studio (close to Eiffel tower)
4          4823489   Close to Eiffel Tower - Beautiful flat : 2 rooms
...            ...                                                ...
279707    38338635  Appartement T2 neuf prÃÂ¨s du tram T3a Porte ...
279708    38538692                          Cozy Studio in Montmartre
279709    38683356            Nice and cosy mini-appartement in Paris
279710    39659000  Charming apartment near Rue Saint Maur / Oberk...
279711    40219504        Cosy apartment with view on Canal St Martin

         host_id  host_since                 host_location host_response_time  \
0        1466919  2011-12-03  Paris, Ile-de-France, France                NaN
1       10328771  2013-11-29  Paris, Ile-de-France, France                NaN
2       19252768  2014-07-31  Paris, Ile-de-France, France                NaN
3       10668311  2013-12-17  Paris, Ile-de-France, France                NaN
4       24837558  2014-12-14  Paris, Ile-de-France, France                NaN
...          ...         ...                           ...                ...
279707  31161181  2015-04-13  Paris, Ile-de-France, France                NaN
279708  10294858  2013-11-27  Paris, Ile-de-France, France                NaN
279709   2238502  2012-04-27  Paris, Ile-de-France, France                NaN
279710  38633695  2015-07-16  Paris, Ile-de-France, France                NaN
279711   6955618  2013-06-17  Paris, Ile-de-France, France                NaN

        host_response_rate  host_acceptance_rate host_is_superhost  \
0                      NaN                   NaN                 f
1                      NaN                   NaN                 f
2                      NaN                   NaN                 f
3                      NaN                   NaN                 f
4                      NaN                   NaN                 f
...                    ...                   ...               ...
279707                 NaN                   NaN                 f
279708                 NaN                   NaN                 f
279709                 NaN                   NaN                 f
279710                 NaN                   NaN                 f
279711                 NaN                   NaN                 f

        host_total_listings_count  ... minimum_nights maximum_nights  \
0                             1.0  ...              2           1125
1                             1.0  ...              2           1125
2                             1.0  ...              2           1125
3                             1.0  ...              2           1125
4                             1.0  ...              2           1125
...                           ...  ...            ...            ...
279707                        1.0  ...              1              7
279708                        1.0  ...              7             15
279709                        1.0  ...              6             30
279710                        1.0  ...              3             18
279711                        1.0  ...              2              4

       review_scores_rating review_scores_accuracy review_scores_cleanliness  \
0                     100.0                   10.0                      10.0
1                     100.0                   10.0                      10.0
2                     100.0                   10.0                      10.0
3                     100.0                   10.0                      10.0
4                     100.0                   10.0                      10.0
...                     ...                    ...                       ...
279707                100.0                   10.0                      10.0
279708                100.0                   10.0                      10.0
279709                100.0                   10.0                      10.0
279710                100.0                   10.0                      10.0
279711                100.0                   10.0                      10.0

        review_scores_checkin  review_scores_communication  \
0                        10.0                         10.0
1                        10.0                         10.0
2                        10.0                         10.0
3                        10.0                         10.0
4                        10.0                         10.0
...                       ...                          ...
279707                   10.0                         10.0
279708                   10.0                         10.0
279709                   10.0                         10.0
279710                   10.0                         10.0
279711                   10.0                         10.0

       review_scores_location review_scores_value  instant_bookable
0                        10.0                10.0                 f
1                        10.0                10.0                 f
2                        10.0                10.0                 f
3                        10.0                10.0                 f
4                        10.0                10.0                 f
...                       ...                 ...               ...
279707                   10.0                10.0                 f
279708                   10.0                10.0                 f
279709                   10.0                10.0                 f
279710                   10.0                10.0                 f
279711                   10.0                10.0                 f

[279712 rows x 33 columns]>

missing values

In [3]:
df.isna().sum()

listing_id                          0
name                              175
host_id                             0
host_since                        165
host_location                     840
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                 165
host_total_listings_count         165
host_has_profile_pic              165
host_identity_verified            165
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                        29435
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating            91405
review_scores_accuracy          91713
review_scores_cleanliness       91665
review_scores_checkin           91771
review_scores_communication     91687
review_scores_location          91775
review_scores_value             91785
instant_bookable                    0
dtype: int64

how does the data look mathematicaly

In [7]:
df.describe()

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
count,2.797120e+05,2.797120e+05,150930.000000,166625.000000,279547.000000,279712.000000,279712.000000,279712.000000,250277.000000,279712.000000,279712.000000,2.797120e+05,188307.000000,187999.000000,188047.000000,187941.000000,188025.000000,187937.000000,187927.000000
mean,2.638196e+07,1.081658e+08,0.865939,0.827168,24.581612,18.761862,12.595075,3.288736,1.515509,608.792737,8.050967,2.755860e+04,93.405195,9.565476,9.312869,9.701534,9.698593,9.633994,9.335364
std,1.442576e+07,1.108570e+08,0.283744,0.289202,284.041143,32.560343,73.081309,2.133379,1.153080,3441.826611,31.518946,7.282875e+06,10.070437,0.990878,1.146072,0.867434,0.886884,0.833234,1.042625
min,2.577000e+03,1.822000e+03,0.000000,0.000000,0.000000,-34.264400,-99.339630,0.000000,1.000000,0.000000,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.384462e+07,1.720656e+07,0.900000,0.780000,1.000000,-22.964390,-43.198040,2.000000,1.000000,75.000000,1.000000,4.500000e+01,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000
50%,2.767098e+07,5.826911e+07,1.000000,0.980000,1.000000,40.710785,2.382780,2.000000,1.000000,150.000000,2.000000,1.125000e+03,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
75%,3.978485e+07,1.832853e+08,1.000000,1.000000,4.000000,41.908610,28.986730,4.000000,2.000000,474.000000,5.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
max,4.834353e+07,3.901874e+08,1.000000,1.000000,7235.000000,48.904910,151.339810,16.000000,50.000000,625216.000000,9999.000000,2.147484e+09,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

duplicate

In [8]:
df.duplicated().sum()

np.int64(0)

how is the correlation between cols

In [9]:
df.corr(numeric_only=True)

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
listing_id,1.000000,0.582679,-0.014195,0.109949,0.071972,-0.012022,-0.001949,-0.005969,0.006881,0.011471,-0.034967,-0.005873,-0.026382,-0.047476,-0.025831,-0.065647,-0.067393,0.016243,-0.020410
host_id,0.582679,1.000000,-0.082474,0.122923,0.015198,0.005266,0.008961,-0.014839,-0.001526,0.011795,-0.038348,-0.003148,-0.089288,-0.095226,-0.055538,-0.100904,-0.103973,-0.046701,-0.067068
host_response_rate,-0.014195,-0.082474,1.000000,0.321510,0.037986,-0.015872,-0.018426,0.012068,-0.007806,-0.000697,-0.012630,0.000048,0.112409,0.108358,0.118284,0.106289,0.120641,0.091927,0.099234
host_acceptance_rate,0.109949,0.122923,0.321510,1.000000,0.034085,0.073135,-0.003525,-0.008704,-0.045264,-0.039315,-0.045547,0.000307,-0.017294,-0.007801,0.028197,-0.013868,-0.011385,0.005349,0.000529
host_total_listings_count,0.071972,0.015198,0.037986,0.034085,1.000000,-0.042281,0.061737,-0.018868,-0.009910,0.009907,-0.000161,-0.000303,-0.037162,-0.040658,-0.016856,-0.036414,-0.045739,-0.005259,-0.049027
latitude,-0.012022,0.005266,-0.015872,0.073135,-0.042281,1.000000,-0.417783,-0.111880,-0.137463,-0.099278,0.046801,0.001569,-0.034199,-0.007049,-0.035079,-0.023368,-0.011368,-0.043589,-0.022222
longitude,-0.001949,0.008961,-0.018426,-0.003525,0.061737,-0.417783,1.000000,0.009465,0.037800,0.019608,-0.056316,-0.001410,-0.048905,-0.052181,-0.045029,-0.043660,-0.033794,-0.052074,-0.039725
accommodates,-0.005969,-0.014839,0.012068,-0.008704,-0.018868,-0.111880,0.009465,1.000000,0.639102,0.146327,-0.033442,0.003241,0.006420,-0.009308,0.007203,0.004743,-0.000910,0.008774,-0.023706
bedrooms,0.006881,-0.001526,-0.007806,-0.045264,-0.009910,-0.137463,0.037800,0.639102,1.000000,0.143307,-0.010582,0.000872,0.009007,-0.010811,0.002247,0.005562,-0.004753,0.008412,-0.019745
price,0.011471,0.011795,-0.000697,-0.039315,0.009907,-0.099278,0.019608,0.146327,0.143307,1.000000,0.006344,-0.000442,0.015048,-0.000693,0.024328,-0.000243,-0.003262,-0.000609,0.001572
minimum_nights,-0.034967,-0.038348,-0.012630,-0.045547,-0.000161,0.046801,-0.056316,-0.033442,-0.010582,0.006344,1.000000,0.000248,0.000143,-0.000529,-0.013915,-0.001112,-0.001204,-0.008982,-0.004731
maximum_nights,-0.005873,-0.003148,0.000048,0.000307,-0.000303,0.001569,-0.001410,0.003241,0.000872,-0.000442,0.000248,1.000000,-0.002795,-0.003251,-0.002943,-0.002934,-0.002895,0.000397,-0.003954
review_scores_rating,-0.026382,-0.089288,0.112409,-0.017294,-0.037162,-0.034199,-0.048905,0.006420,0.009007,0.015048,0.000143,-0.002795,1.000000,0.785838,0.740594,0.661642,0.709482,0.540717,0.782864
review_scores_accuracy,-0.047476,-0.095226,0.108358,-0.007801,-0.040658,-0.007049,-0.052181,-0.009308,-0.010811,-0.000693,-0.000529,-0.003251,0.785838,1.000000,0.647809,0.655795,0.682926,0.532866,0.717447
review_scores_cleanliness,-0.025831,-0.055538,0.118284,0.028197,-0.016856,-0.035079,-0.045029,0.007203,0.002247,0.024328,-0.013915,-0.002943,0.740594,0.647809,1.000000,0.525337,0.540806,0.430433,0.654149
review_scores_checkin,-0.065647,-0.100904,0.106289,-0.013868,-0.036414,-0.023368,-0.043660,0.004743,0.005562,-0.000243,-0.001112,-0.002934,0.661642,0.655795,0.525337,1.000000,0.736436,0.519118,0.595167
review_scores_communication,-0.067393,-0.103973,0.120641,-0.011385,-0.045739,-0.011368,-0.033794,-0.000910,-0.004753,-0.003262,-0.001204,-0.002895,0.709482,0.682926,0.540806,0.736436,1.000000,0.520654,0.634834
review_scores_location,0.016243,-0.046701,0.091927,0.005349,-0.005259,-0.043589,-0.052074,0.008774,0.008412,-0.000609,-0.008982,0.000397,0.540717,0.532866,0.430433,0.519118,0.520654,1.000000,0.532644
review_scores_value,-0.020410,-0.067068,0.099234,0.000529,-0.049027,-0.022222,-0.039725,-0.023706,-0.019745,0.001572,-0.004731,-0.003954,0.782864,0.717447,0.654149,0.595167,0.634834,0.532644,1.000000

In [ ]:
df['name'] = df['name'].fillna('Unknown')
df['name']

KeyError: "None of [Index(['Beautiful Flat in le Village Montmartre, Paris',\n       '39 mÃ\x82Â² Paris (Sacre CÃ\x85â\x80\x9cur)',\n       'Lovely apartment with Terrace, 60m2',\n       'Cosy studio (close to Eiffel tower)',\n       'Close to Eiffel Tower - Beautiful flat : 2 rooms',\n       'NEW - Charming apartment Le Marais',\n       '2P - Entre Bastille et Republique',\n       '57sqm btw. Bastille & PÃ\x83Â¨re Lachaise',\n       'Charming appartment near the Parc Buttes Chaumont',\n       'Bel appartement plein de charme !',\n       ...\n       'Appartement charme Haussmanien Alesia.', 'Nid douillet Montorgueil',\n       'Appartement Paris 20Ã\x83Â¨me',\n       'Charmant appartement parisien sous les toits',\n       'cocoon, cozy & surf spirit',\n       'Appartement T2 neuf prÃ\x83Â¨s du tram T3a Porte Didot',\n       'Cozy Studio in Montmartre', 'Nice and cosy mini-appartement in Paris',\n       'Charming apartment near Rue Saint Maur / Oberkampf',\n       'Cosy apartment with view on Canal St Martin'],\n      dtype='str', length=279712)] are in the [index]"

In [13]:
df.isna().sum()

listing_id                          0
name                              175
host_id                             0
host_since                        165
host_location                     840
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                 165
host_total_listings_count         165
host_has_profile_pic              165
host_identity_verified            165
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                        29435
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating            91405
review_scores_accuracy          91713
review_scores_cleanliness       91665
review_scores_checkin           91771
review_scores_communication     91687
review_scores_location          91775
review_scores_value             91785
instant_bookable                    0
dtype: int64